### ISSUE TITLE
Fix Admin Web Interface

### ISSUE THREAD

**Issue by d1m0** [chezbob/chezbob-legacy#15]
Bring the web interface back up. Apply changes to bring it up to a current version of Django

**Comment by thalvors** [comment]
Basic web is up, see http://soda.ucsd.edu.  There are two issues stopping the admin interface right now.  We cannot connect over SSL due to the port being blocked on the router, we should set it to forward all traffic to soda and use ufw from there.  Once that's fixed, our cert is valid for chezbob.ucsd.edu, not soda.ucsd.edu.  We probably just need to redirect chezbob's A record to be the same as soda's, but maybe there's a better option.

**Comment by kmowery** [comment]
Did you commit the configuration changes as an ansible script? I don't see them but don't have time to look very hard...

**Comment by thalvors** [comment]
I did not set them up in ansible yet, sorry!  I'll do that before closing this issue.

The web interface is working, go to https://soda.ucsd.edu/admin/.  Unfortunately the cert is for chezbob.ucsd.edu so you'll have to tell your browser to accept the cert.  I'm not sure where chezbob.ucsd.edu points but i appears to not be to the same router, the right solution is probably to update where this record points to the same spot as soda.ucsd.edu.  (I assume we can't use a CNAME because of the cert?)  I'll email csehelp and see who we can talk to about this.

**Comment by jdeblasio** [comment]
This appears to be fixed, so I'm going to close it. Re-open if needed, but the cert (which is no longer liked by chrome because of SHA-1) matches chezbob.ucsd.edu and the admin interface works properly there.
